### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/tomato#106]
The below query returns a 502

https://tomato.bmltenabled.org/main_server/client_interface/json/?switcher=GetServiceBodies&services[]=106&services[]=107&services[]=1150&services[]=1151&services[]=122&services[]=123&services[]=125&services[]=127&services[]=128&services[]=129&services[]=130&services[]=131&services[]=132&services[]=133&services[]=134&services[]=135&services[]=1351&services[]=1352&services[]=136&services[]=1364&services[]=137&services[]=140&services[]=141&services[]=142&services[]=143&services[]=144&services[]=145&services[]=146&services[]=147&services[]=148&services[]=149&services[]=150&services[]=151&services[]=152&services[]=153&services[]=154&services[]=155&services[]=156&services[]=157&services[]=158&services[]=159&services[]=160&services[]=161&services[]=162&services[]=163&services[]=165&services[]=166&services[]=167&services[]=168&services[]=169&services[]=170&services[]=172&services[]=173&services[]=174&services[]=175&services[]=176&services[]=1800&services[]=1801&services[]=1932&services[]=395&services[]=397&services[]=398&services[]=399&services[]=400&services[]=401&services[]=402&services[]=403&services[]=404&services[]=405&services[]=406&services[]=407&services[]=409&services[]=410&services[]=411&services[]=412&services[]=413&services[]=414&services[]=415&services[]=417&services[]=418&services[]=419&services[]=427&services[]=428&services[]=429&services[]=430&services[]=431&services[]=432&services[]=433&services[]=434&services[]=435&services[]=667&services[]=668&services[]=669&services[]=671&services[]=673&services[]=674&services[]=675&services[]=676&services[]=678&services[]=679&services[]=680&services[]=793

**Comment by jbraswell** [comment]
This is the error from cloudwatch

```
invalid request block size: 4851 (max 4096)...skip
```

**Comment by jbraswell** [comment]
From https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html

```
By default uWSGI allocates a very small buffer (4096 bytes) for the headers of each request. If you start receiving “invalid request block size” in your logs, it could mean you need a bigger buffer. Increase it (up to 65535) with the buffer-size option.
```

Working on increasing this by 4x now

**Comment by jbraswell** [comment]
This is fixed by https://github.com/bmlt-enabled/tomato/commit/95e29baea0f54826b2db9a5d4ad12aa72ecd3462. Fix is deployed.

**Comment by radius314** [comment]
Thanks for the quick response.
