### ISSUE TITLE
Intermittent HTTP 500 error response code.

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/tomato#131]
I have noticed today I am occasionally getting 500 errors on paginated results similar to the query below.  

https://tomato.bmltenabled.org/main_server/client_interface/json/?switcher=GetSearchResults&data_field_key=root_server_uri,longitude,latitude,id_bigint,formats,meeting_name,weekday_tinyint,start_time&page_num=23&page_size=1000

Here are the full request headers (in case you need them for request tracing).

```shell
curl 'https://tomato.bmltenabled.org/main_server/client_interface/json/?switcher=GetSearchResults&data_field_key=root_server_uri,longitude,latitude,id_bigint,formats,meeting_name,weekday_tinyint,start_time&page_num=23&page_size=1000' \
  -H 'authority: tomato.bmltenabled.org' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'accept: */*' \
  -H 'origin: http://localhost:8002' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: http://localhost:8002/' \
  -H 'accept-language: en-US,en;q=0.9' \
  --compressed
```

**Comment by jbraswell** [comment]
Likely memory errors. Not much we can do with large queries without additional funding or moving to much, much cheaper hosting.
