### ISSUE TITLE
Consider Moving the Server List JSON File to Its Own Repo

### ISSUE THREAD

**Issue by ChrisMarshallNY** [bmlt-enabled/tomato#142]
This reflects a brief Slack discussion between myself and @pjaudiomv.

[The Server List JSON File](https://github.com/bmlt-enabled/tomato/blob/master/rootServerList.json) may have uses beyond just TOMATO. For instance, it might be leveraged by a plugin or Web widget that displays links to all the Semantic Workshops for Root Servers (as well as things like versions and whatnot, like the Tally).

If we broke the file out to its own repo, it would make it more of a "public resource." Watching it would guarantee that you only get notified when a Root Server changes.

**Comment by jbraswell** [comment]
Not going to do this, it woulda make things more complex. Tomato itself uses the raw GitHub URL. Other apps can do the same.

https://github.com/bmlt-enabled/tomato/blob/767398d5aa47df7ec72acbee24f9159f8843110c/src/tomato/api/management/commands/import_root_servers.py#L95
