### ISSUE TITLE
NAWS CSV Testing

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/tomato#36]
I noticed the naws dump its duplicating formats when a meeting is marked with a D in the delete column, this doesn't happen every time but alot.

**Comment by jbraswell** [comment]
Will you provide a link that does this?

**Comment by pjaudiomv** [comment]
![screen shot 2018-12-27 at 10 55 49 am](https://user-images.githubusercontent.com/34245618/50486060-07c47180-09c6-11e9-9835-7910005cada7.png)

**Comment by pjaudiomv** [comment]
https://tomato.na-bmlt.org/main_server/client_interface/csv/?switcher=GetNAWSDump&sb_id=666

https://www.nerna.org/main_server/client_interface/csv/?switcher=GetNAWSDump&sb_id=1

**Comment by pjaudiomv** [comment]
I just sorted by committee code, then committee name and did used beyond compare on them

**Comment by radius314** [comment]
What the latest with this, interested in the status.
