### ISSUE TITLE
add jsonp

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/tomato#37]
would be nice to have json with padding added

**Comment by jbraswell** [comment]
jsonp exists. Is there a specific endpoint that isn’t working?

**Comment by pjaudiomv** [comment]
ah wtf, I would of used that months ago. I must of never actually tried to use it.
if I go to [https://tomato.na-bmlt.org/main_server/client_interface/jsonp/?switcher=GetSearchResults&weekdays=1&formats=1`](https://tomato.na-bmlt.org/main_server/client_interface/jsonp/?switcher=GetSearchResults&weekdays=1&formats=1) I just get a blank page however if I go to [https://bmlt.sezf.org/main_server/client_interface/jsonp/?switcher=GetSearchResults&formats=1](https://bmlt.sezf.org/main_server/client_interface/jsonp/?switcher=GetSearchResults&formats=1) I get a response. this is why i thought it didnt work. However after applying an actual callback to it, I found yes indeed it works fine. [https://tomato.na-bmlt.org/main_server/client_interface/jsonp/?switcher=GetSearchResults&weekdays=1&formats=1&callback=cb](https://tomato.na-bmlt.org/main_server/client_interface/jsonp/?switcher=GetSearchResults&weekdays=1&formats=1&callback=cb)

**Comment by pjaudiomv** [comment]
I totes would of used that for tomato tally
