### ISSUE TITLE
GetSearchResults not letting me get single meeting data

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/tomato#39]
when trying to get meeting info for either single meeting or multiple meetings by meeting ID it just starts giving me all the meeting data so for example `GetSearchResults&meeting_ids[]=12214` or `GetSearchResults&meeting_ids[]=12214&meeting_ids[]=12215` doesn't give me what I want.

**Comment by pjaudiomv** [comment]
Just for reference example on nerna
https://www.nerna.org/main_server/client_interface/json/?switcher=GetSearchResults&meeting_ids[]=513

https://www.nerna.org/main_server/client_interface/json/?switcher=GetSearchResults&meeting_ids[]=513&meeting_ids[]=514

**Comment by jbraswell** [comment]
This is implemented and pushed to tomato.
