### ISSUE TITLE
default sorts arent correct

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/tomato#40]
I think default sorting is set in here c_comdef_meetings.class.php. going to look more into it

this is example of exact same queries one on nerna.org and one on tomato. nerna is sorted by time tomato is not

https://www.nerna.org/main_server/client_interface/csv/?switcher=GetSearchResults&weekdays=2

https://tomato.na-bmlt.org/main_server/client_interface/csv/?switcher=GetSearchResults&services[]=666&services[]=672&services[]=673&services[]=674&services[]=675&services[]=667&services[]=668&services[]=676&services[]=669&services[]=671&services[]=677&services[]=680&services[]=678&services[]=679&weekdays=2

**Comment by jbraswell** [comment]
This is fixed and deployed.
