### ISSUE TITLE
Allow CORS for REST API

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/tomato#41]

**Comment by pjaudiomv** [comment]
http://jpadilla.github.io/django-rest-framework-jsonp/

**Comment by jbraswell** [comment]
In Django CORS exceptions are generally implemented using the `django-cors-headers` package. I was under the impression I had already implemented this on tomato.

**Comment by pjaudiomv** [comment]
oh yes my bad we have had this conversation, ill test it out. it really only ever needs to work for tally so even if it needed authentication or some shit but whatever ill check it out. I don't remember it getting implemented but i believe you.

**Comment by pjaudiomv** [comment]
yup its installed just checked cool, ill try it out.

**Comment by jbraswell** [comment]
https://github.com/bmlt-enabled/tomato/blob/master/src/tomato/settings/__init__.py#L186

**Comment by pjaudiomv** [comment]
yes works fine :)

**Comment by pjaudiomv** [comment]
cool I think this can be closed now.

**Comment by radius314** [comment]
I have opened #42 to address the gaps.
