### ISSUE TITLE
data_key_field support

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/tomato#45]
The root server supports a parameter that allows you to specify individual fields that you want to return in GetSearchResults.  

For example:
```switcher=GetSearchResults&data_key_field=longitude,latitude,id_bigint,meeting_name,weekday_tinyint,start_time&services[]=101```

When the following request is made it should only return the fields listed.

**Comment by pjaudiomv** [comment]
Whats it giving fit a response now, that's what I did for my version of tomato tally
https://github.com/bmlt-enabled/tomato-tally/blob/0e6c54733522099dee2a73839dffb0ba0cbd6447/map.php#L4..L9

**Comment by pjaudiomv** [comment]
Maybe that's an additional reason it took so long to load

**Comment by radius314** [comment]
Yes it’s very slow.  I thought about chunking the response, with pagination.

**Comment by jbraswell** [comment]
For some reason I thought this was implemented. I will look into it shortly.

**Comment by pjaudiomv** [comment]
Maybe it's just not working for the '&services[]' part

**Comment by radius314** [comment]
Even without that it’s returning all.  Are you seeing differently?

**Comment by jbraswell** [comment]
In tomato it's called `data_field_key`, not `data_key_field`.

**Comment by radius314** [comment]
Thanks.

**Comment by jbraswell** [comment]
Looks like it's also `data_field_key` in the BMLT Root Server.
