### ISSUE TITLE
distance_in_miles and distance_in_km not returning when using data_field_key

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/tomato#46]
The below query does not return the calculated fields `distance_in_miles` and `distance_in_km` when using them in the `data_field_key` parameter.

```
/client_interface/json/?switcher=GetSearchResults&data_field_key=distance_in_miles,root_server_uri,service_body_bigint&sort_results_by_distance=1&geo_width=-10&long_val=-78.64224910497873&lat_val=35.54187117496469
```

**Comment by pjaudiomv** [comment]
this is still broken and it upsets me @jbraswell

**Comment by pjaudiomv** [comment]
:) 

`https://www.nerna.org/main_server/client_interface/json/?switcher=GetSearchResults&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_info,location_municipality,location_province,location_street,longitude,latitude,distance_in_miles,distance_in_km&sort_results_by_distance=1&long_val=-70.5502916&lat_val=41.363871&geo_width=-50&weekdays=1`

:(

`https://tomato.bmltenabled.org/main_server/client_interface/json/?switcher=GetSearchResults&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_info,location_municipality,location_province,location_street,longitude,latitude,distance_in_miles,distance_in_km&sort_results_by_distance=1&long_val=-70.5502916&lat_val=41.363871&geo_width=-50&weekdays=1`

**Comment by radius314** [comment]
Circling back on this to see on this progress.

Looking to implement a new feature (https://github.com/bmlt-enabled/yap/issues/358) in Yap that would allow you to display the distance to a meeting in SMS.  If someone decides to use to Tomato for this feature it will return 0 mi / 0 km.

Sample query: https://tomato.na-bmlt.org/main_server/client_interface/json/?switcher=GetSearchResults&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_info,location_municipality,location_province,location_street,longitude,latitude,distance_in_miles,distance_in_km&sort_results_by_distance=1&long_val=-78.9525533&lat_val=36.2862387&geo_width=50&weekdays=3

![Out to Lunch Tuesday 1200 PM, 2501 Clark Ave , Raleigh, NC (0 mi  0 km)](https://user-images.githubusercontent.com/1850811/71623544-57c2af00-2bab-11ea-9192-fec47e18ea01.jpeg)

**Comment by pjaudiomv** [comment]
```python
from geopy.distance import geodesic


origin = (30.172705, 31.526725)  # (latitude, longitude) don't confuse
dist = (30.288281, 31.732326)

print(geodesic(origin, dist).kilometers)  # 23.576805481751613
print(geodesic(origin, dist).miles)  # 14.64994773134371
```

**Comment by pjaudiomv** [comment]
https://stackoverflow.com/questions/19412462/getting-distance-between-two-points-based-on-latitude-longitude

**Comment by jbraswell** [comment]
This is going to be calculated by the database, not in python. Doing it in python would require iterating every single result and doing a calculation. Algorithmically, that's pretty bad, and it'd cause memory problems because currently we're streaming from the cursor to the browser rather than loading it all into python memory. I've already implemented most of this in another branch - just need to pick it back up.

**Comment by pjaudiomv** [comment]
Ahh yes that makes sense, 👃

**Comment by pjaudiomv** [comment]
would you use the `ST_Distance` sql function for this, just curious as this field is dynamically populated based off the query string input which could be millions of different combinations.

**Comment by jbraswell** [comment]
I’d have to look at the open merge request to see how I did it

**Comment by jbraswell** [comment]
...I think I finally finished this. Can you guys do some testing?

These should work as `data_field_keys` when any of the geo based queries are run...
1. `SearchString` with `StringSearchIsAnAddress`
2. `lat_val` and `long_val`
3. `lat_val` and `long_val` with `geo_width` or `geo_width_km`

In addition to general genera testing and testing the scenarios above, we should also validate that...
1. Normal `data_field_keys` queries still work
2. Sorting by various fields still works (`sort_keys`)
