### ISSUE TITLE
Counts of meetings + groups by service body.

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/tomato#71]
Tomato does a really good job of counting things.  To take this a step further and to assist in counting efforts I think it might be a good idea to be able to query the number of meetings and groups at the service body level.

Some thoughts arise with this, for example would it aggregate at the regional or zonal level if counting areas?

There are a few service bodies in Tomato that aren't being categorized right now (at least one LSU i noticed).

**Comment by radius314** [comment]
For counting groups it could be taking a similar approach that crouton takes, which is sort of a guess approach.  First it will try to link up world IDs, and then after that meeting_name.

https://github.com/bmlt-enabled/crouton/blob/master/croutonjs/src/js/crouton-core.js#L495-L504

**Comment by jbraswell** [comment]
This can all be done with the ORM. I’ll extend the REST API. Counts on a database this size are cheap in Postgres so long as proper indexes are in place.
