### ISSUE TITLE
Tomato bombs on meeting searches with multiple formats

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/tomato#82]
When trying to query tomato for multiple formats I get the white screen of death.

Ex `https://tomato.bmltenabled.org/main_server/client_interface/json/?switcher=GetSearchResults&formats[]=1750&formats[]=1670`

however one format works fine

`https://tomato.bmltenabled.org/main_server/client_interface/json/?switcher=GetSearchResults&formats[]=1750`

and

`https://tomato.bmltenabled.org/main_server/client_interface/json/?switcher=GetSearchResults&formats[]=1670`

this is blocking me from doing my work.

**Comment by jbraswell** [comment]
working as intended

**Comment by pjaudiomv** [comment]
its an AND not a OR, damn logic
