### ISSUE TITLE
GetSearchResults endpoint not respecting the "lang_enum" parameter when "get_used_formats" parameter is used.

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/tomato#84]
**This query should return the formats with Spanish language response for the formats as it does on a root server.**

https://.../main_server/client_interface/json?switcher=GetSearchResults&get_used_formats&lang_enum=es&data_field_key=location_postal_code_1,duration_time,start_time,weekday_tinyint,service_body_bigint,longitude,latitude,location_province,location_municipality,location_street,location_info,location_text,location_neighborhood,formats,format_shared_id_list,comments,meeting_name,location_sub_province,worldid_mixed,root_server_uri,id_bigint,meeting_name,location_text,formatted_address,formatted_location_info,virtual_meeting_link,virtual_meeting_link,show_qrcode,virtual_meeting_link,phone_meeting_number,phone_meeting_number,show_qrcode,phone_meeting_number,latitude,longitude,latitude,longitude,map_word,latitude,longitude&services[]=735&services[]=736&recursive=1&sort_keys=start_time

**This request works on the SEZF root server, because it returns the formats in Spanish**

https://.../main_server/client_interface/json?switcher=GetSearchResults&get_used_formats&lang_enum=es&data_field_key=location_postal_code_1,duration_time,start_time,weekday_tinyint,service_body_bigint,longitude,latitude,location_province,location_municipality,location_street,location_info,location_text,location_neighborhood,formats,format_shared_id_list,comments,meeting_name,location_sub_province,worldid_mixed,root_server_uri,id_bigint,meeting_name,location_text,formatted_address,formatted_location_info,virtual_meeting_link,virtual_meeting_link,show_qrcode,virtual_meeting_link,phone_meeting_number,phone_meeting_number,show_qrcode,phone_meeting_number,latitude,longitude,latitude,longitude,map_word,latitude,longitude&services[]=44&services[]=45&recursive=1&sort_keys=start_time

**Comment by radius314** [comment]
any chance this could be worked on soon?  I'd like push out crouton 3.11.0 which has a few coupled commits.

**Comment by jbraswell** [comment]
I’ll do an investigation of the required changes today. Depending on outcome, it could be done this week.

**Comment by radius314** [comment]
lgtm, thanks
