### ISSUE TITLE
Service body returned in Semantic API, but not Tomato API call.

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/tomato#86]
This Semantic request returns the service body ID 1754

https://tomato.bmltenabled.org/main_server/client_interface/json/?switcher=GetServiceBodies

However this Tomato API call does not.

https://tomato.bmltenabled.org/rest/v1/servicebodies/

This does though.

https://tomato.bmltenabled.org/rest/v1/servicebodies/1754

**Comment by jbraswell** [comment]
It's on page 2 https://tomato.bmltenabled.org/rest/v1/servicebodies/?page=2

**Comment by jbraswell** [comment]
Notice that the payload at https://tomato.bmltenabled.org/rest/v1/servicebodies/ contains a `"next"` key with the link to the second page.

**Comment by radius314** [comment]
thanks, will take a look at that.

**Comment by jbraswell** [comment]
https://www.youtube.com/watch?v=EF8GhC-T_Mo

**Comment by radius314** [comment]
😂

**Comment by radius314** [comment]
this worked good, thanks
